### ISSUE TITLE
ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()

### ISSUE THREAD

**Issue by penaivanalejandro** [freeacs/freeacs#143]
When a new job is created, for example, Type: Config, and when the job is finished, the Core log starts to mark the following errors:

```LOG
2018-06-20 12:15:41 [JobRuleEnforcer] INFO c.g.f.core.task.JobRuleEnforcer - JobRuleEnforcer: Detected status change in job ProvB310 (1), new status is COMPLETED
2018-06-20 12:16:10 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run ()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.DBI.cleanup (DBI.java:283)
at com.github.freeacs.dbi.DBI.run (DBI.java:353)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:10 [ScriptExecutor] ERROR c.g.freeacs.core.task.ScriptExecutor - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.ScriptExecutions.getNotStartedExecutions (ScriptExecutions.java:106)
at com.github.freeacs.core.task.ScriptExecutor.processScripts (ScriptExecutor.java:120)
at com.github.freeacs.core.task.ScriptExecutor.runImpl (ScriptExecutor.java:103)
at com.github.freeacs.core.task.DBIShare.run (DBIShare.java:71)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:11 [JobRuleEnforcer] ERROR c.g.f.core.task.JobRuleEnforcer - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.UnitJobs.markAsUnconfirmed (UnitJobs.java:206)
at com.github.freeacs.core.task.JobRuleEnforcer.process (JobRuleEnforcer.java:221)
at com.github.freeacs.core.task.JobRuleEnforcer.runImpl (JobRuleEnforcer.java:168)
at com.github.freeacs.core.task.DBIOwner.run (DBIOwner.java:75)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:11 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run ()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.DBI.populateInboxes (DBI.java:240)
at com.github.freeacs.dbi.DBI.run (DBI.java:346)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:11 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run ()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.DBI.populateInboxes (DBI.java:240)
at com.github.freeacs.dbi.DBI.run (DBI.java:346)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:11 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run ()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:676)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:190)
at com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:155)
at com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:128)
at com.github.freeacs.dbi.DBI.populateInboxes (DBI.java:240)
at com.github.freeacs.dbi.DBI.run (DBI.java:346)
at java.lang.Thread.run (Thread.java:748)
2018-06-20 12:16:11 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run ()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hik
```

Attach the log for more info...

[shell.log](https://github.com/freeacs/freeacs/files/2120392/shell.log)

**Comment by jarlah** [comment]
Thanks for report:) i am thankful for all the testing that is done.

This looks like a variant of the other connection leakage bug i fixed. I will check if line numbers match with master.

**Comment by jarlah** [comment]
i have a wild guess that there is a lot of things happening at the same time in core that makes hikari run out of resources. I have tried hard to spot leakage errors with no luck currently. Are you absolutely sure you are running latest versions? I remembered we fixed an obvious bug by just poking around in web and then core crashed. Didnt we? And now we have a more subtle bug, that is introduced possibly because there is a lot of asynchronous tasks running in core that each takes up x amount of connections really fast. Ill have to debug more some other day, but deploy latest binaries/images.

**Comment by penaivanalejandro** [comment]
Hello Jarl, I pass the image of how I configure FreeACS (web) and start to mark the error ...

Possibly it's my mistake that I'm setting it up badly, but I'm still testing with the Huawei B310 modem in one way or another to be able to register it in FreeACS.

![job_error](https://user-images.githubusercontent.com/29745524/41689192-12d1d7bc-74b5-11e8-870c-53b07b2c8608.png)

**Comment by jarlah** [comment]
I am not sure what the IGD.Name is and why its a dropdown where you have selected GetParameterAttributes.  I guess its just test data? 

Anyway, I ask you to edit /etc/default/freeacs-core by adding 
```MAIN_DATASOURCE_MAXIMUM-POOL-SIZE=30```

And rinse and repeat the process. By doing this we can check if its a constant connection leakage or if core is so connection intensive that it never lets hikari breath up until a point where the demand for connections is lower than the available connections.

**Comment by penaivanalejandro** [comment]
Hi @jarlah good day,

I did what you asked for, add the POOL-SIZE line and restart the service.
![core_config](https://user-images.githubusercontent.com/29745524/41730972-c4ac5a10-7542-11e8-8468-901e5753d4f3.png)


Then add the following job on the web:
![job_error_2](https://user-images.githubusercontent.com/29745524/41730975-ca008496-7542-11e8-8af0-588b696fb1f5.png)


And now when you stop the job, you start to mark the following in the core log:

```LOG
2018-06-21 10:56:16 [JobRuleEnforcer] INFO  c.g.f.core.task.JobRuleEnforcer - JobRuleEnforcer: Detected status change in job TestB12313 (1), new status is COMPLETED
2018-06-21 10:56:30 [TriggerReleaser] INFO  c.g.f.core.task.TriggerReleaser - TriggerReleaser: Trigger processing starts...
2018-06-21 10:56:46 [ScriptExecutor] ERROR c.g.freeacs.core.task.ScriptExecutor - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.ScriptExecutions.getNotStartedExecutions(ScriptExecutions.java:106)
	at com.github.freeacs.core.task.ScriptExecutor.processScripts(ScriptExecutor.java:120)
	at com.github.freeacs.core.task.ScriptExecutor.runImpl(ScriptExecutor.java:103)
	at com.github.freeacs.core.task.DBIShare.run(DBIShare.java:71)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:46 [JobRuleEnforcer] ERROR c.g.f.core.task.JobRuleEnforcer - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.UnitJobs.markAsUnconfirmed(UnitJobs.java:206)
	at com.github.freeacs.core.task.JobRuleEnforcer.process(JobRuleEnforcer.java:221)
	at com.github.freeacs.core.task.JobRuleEnforcer.runImpl(JobRuleEnforcer.java:168)
	at com.github.freeacs.core.task.DBIOwner.run(DBIOwner.java:75)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:46 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.DBI.populateInboxes(DBI.java:240)
	at com.github.freeacs.dbi.DBI.run(DBI.java:346)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:46 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.DBI.populateInboxes(DBI.java:240)
	at com.github.freeacs.dbi.DBI.run(DBI.java:346)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:46 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.DBI.populateInboxes(DBI.java:240)
	at com.github.freeacs.dbi.DBI.run(DBI.java:346)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:47 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.DBI.populateInboxes(DBI.java:240)
	at com.github.freeacs.dbi.DBI.run(DBI.java:346)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:56:47 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run()
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.DBI.populateInboxes(DBI.java:240)
	at com.github.freeacs.dbi.DBI.run(DBI.java:346)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:00 [TriggerReleaser] ERROR c.g.f.core.task.TriggerReleaser - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30004ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.Triggers.deleteEvents(Triggers.java:211)
	at com.github.freeacs.dbi.Triggers.deleteEvents(Triggers.java:196)
	at com.github.freeacs.core.task.TriggerReleaser.processAllTriggers(TriggerReleaser.java:83)
	at com.github.freeacs.core.task.TriggerReleaser.runImpl(TriggerReleaser.java:30)
	at com.github.freeacs.core.task.DBIShare.run(DBIShare.java:71)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:15 [DeleteOldScripts] ERROR c.g.f.core.task.DeleteOldScripts - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.ScriptExecutions.deleteExecutions(ScriptExecutions.java:284)
	at com.github.freeacs.core.task.DeleteOldScripts.deleteOldScripts(DeleteOldScripts.java:35)
	at com.github.freeacs.core.task.DeleteOldScripts.runImpl(DeleteOldScripts.java:22)
	at com.github.freeacs.core.task.DBIShare.run(DBIShare.java:71)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:16 [ScriptExecutor] ERROR c.g.freeacs.core.task.ScriptExecutor - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.ScriptExecutions.getNotStartedExecutions(ScriptExecutions.java:106)
	at com.github.freeacs.core.task.ScriptExecutor.processScripts(ScriptExecutor.java:120)
	at com.github.freeacs.core.task.ScriptExecutor.runImpl(ScriptExecutor.java:103)
	at com.github.freeacs.core.task.DBIShare.run(DBIShare.java:71)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:17 [JobRuleEnforcer] ERROR c.g.f.core.task.JobRuleEnforcer - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.UnitJobs.markAsUnconfirmed(UnitJobs.java:206)
	at com.github.freeacs.core.task.JobRuleEnforcer.process(JobRuleEnforcer.java:221)
	at com.github.freeacs.core.task.JobRuleEnforcer.runImpl(JobRuleEnforcer.java:168)
	at com.github.freeacs.core.task.DBIOwner.run(DBIOwner.java:75)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:17 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:17 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:17 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:18 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:18 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:30 [TriggerReleaser] INFO  c.g.f.core.task.TriggerReleaser - TriggerReleaser: Trigger processing starts...
2018-06-21 10:57:46 [ScriptExecutor] ERROR c.g.freeacs.core.task.ScriptExecutor - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.ScriptExecutions.getNotStartedExecutions(ScriptExecutions.java:106)
	at com.github.freeacs.core.task.ScriptExecutor.processScripts(ScriptExecutor.java:120)
	at com.github.freeacs.core.task.ScriptExecutor.runImpl(ScriptExecutor.java:103)
	at com.github.freeacs.core.task.DBIShare.run(DBIShare.java:71)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:48 [JobRuleEnforcer] ERROR c.g.f.core.task.JobRuleEnforcer - An error occurred
java.sql.SQLTransientConnectionException: mainPool - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at com.github.freeacs.dbi.UnitJobs.markAsUnconfirmed(UnitJobs.java:206)
	at com.github.freeacs.core.task.JobRuleEnforcer.process(JobRuleEnforcer.java:221)
	at com.github.freeacs.core.task.JobRuleEnforcer.runImpl(JobRuleEnforcer.java:168)
	at com.github.freeacs.core.task.DBIOwner.run(DBIOwner.java:75)
	at java.lang.Thread.run(Thread.java:748)
2018-06-21 10:57:48 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:48 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:48 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:49 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.
2018-06-21 10:57:49 [DBI for Core] ERROR com.github.freeacs.dbi.DBI - An error occurred in DBI.run() (stacktrace printed earlier): mainPool - Connection is not available, request timed out after 30000ms.

```

**Comment by jarlah** [comment]
Ok. I am abroad now, and it can take some time for me the dig into this. While I am abroad I am focusing on other issues. I thank you for your ongoing testing and patience. We will fix this, but its a tiny bit slow process with only 1 developer that can only work in between other real life work ;)

**Comment by jarlah** [comment]
Finally got some spare time to look at this. And then I nailed it. I have found the problem. it actually was a connection leakage issue. I had forgot to add closing of connections in job related sql code. I will plan to make a new tag and update binaries and docker images in RC12.

**Comment by jarlah** [comment]
@penaivanalejandro ready for retest/verification. I had to remove the rpm packages from the release since i do not own a machine atm that can build rpm packages easily. But i guess you are either using ubuntu deb packages or docker. If you are using centos, you can convert deb to rpm via alien.

**Comment by jarlah** [comment]
added back rpms.

**Comment by penaivanalejandro** [comment]
Thanks @jarlah i will testing tomorrow, I use ubuntu deb packages today.
Again...  Thanks so much for your support.

**Comment by penaivanalejandro** [comment]
Hi @jarlah I test the fix...  and it's working...


```LOG
2018-07-04 18:40:47 [JobRuleEnforcer] INFO  c.g.f.core.task.JobRuleEnforcer - JobRuleEnforcer: Found new job: testNokia (1)
2018-07-04 18:40:53 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - Before cleanup stats (total=12, active=0, idle=12, waiting=0)
2018-07-04 18:40:53 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - After cleanup  stats (total=12, active=0, idle=12, waiting=0)
2018-07-04 18:41:10 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - 1 messages was deleted from message table
2018-07-04 18:41:14 [mainPool connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - mainPool - Closing connection com.mysql.cj.jdbc.ConnectionImpl@3ec9feb8: (connection has passed maxLifetime)
2018-07-04 18:41:23 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - Before cleanup stats (total=11, active=0, idle=11, waiting=0)
2018-07-04 18:41:23 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - After cleanup  stats (total=11, active=0, idle=11, waiting=0)
2018-07-04 18:41:30 [TriggerReleaser] INFO  c.g.f.core.task.TriggerReleaser - TriggerReleaser: Trigger processing starts...
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:32 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:32 [JobRuleEnforcer] INFO  c.g.f.core.task.JobRuleEnforcer - JobRuleEnforcer: Detected status change in job testNokia (1), new status is PAUSED
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.Inbox - Message: [MTYPE: PUBLISH-CHG, OTYPE: JOB, FROM: Web, TO: ALL, OBJECTID: 1] was added to an inbox
2018-07-04 18:41:36 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - DBI discovered that JOB with id = 1 has changed (PUBLISH-CHG) (sent from Web)
2018-07-04 18:41:36 [JobRuleEnforcer] INFO  c.g.f.core.task.JobRuleEnforcer - JobRuleEnforcer: Detected status change in job testNokia (1), new status is COMPLETED
2018-07-04 18:41:45 [DeleteOldScripts] DEBUG c.g.f.core.task.DeleteOldScripts - DeleteOldScripts: No old script executions deleted
2018-07-04 18:41:48 [DBI for Core] DEBUG com.github.freeacs.dbi.DBI - 1 messages was deleted from message table
2018-07-04 18:41:53 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - Before cleanup stats (total=11, active=0, idle=11, waiting=0)
2018-07-04 18:41:53 [mainPool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - mainPool - After cleanup  stats (total=11, active=0, idle=11, waiting=0)

```
