### ISSUE TITLE
Docker installation monitor not available

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [freeacs/freeacs#159]
after you press : Monitor in web gui you will get : 

The page could not be displayed
Monitor Service is not running! 
Log extract : 

`
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
2018-07-31 13:29:51 [qtp2124448375-62] INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
2018-07-31 13:29:51 [qtp2124448375-62] WARN  c.g.f.w.app.page.monitor.MonitorPage - Could not find the monitor server
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
........
'

**Comment by jarlah** [comment]
yes i am aware of it. the monitor service was removed at one point, in addition to some other services that i also dont want to continue supporting. I am currently thinking about what i can replace it with. 

If you are in docker, you can verify that services are running by issuing docker ps in command line and inspecting output.

**Comment by jarlah** [comment]
Going to bring back the monitor service, but it will be redesigned to work with spring boot actuator endpoints, which are much better to assess system status.

**Comment by jarlah** [comment]
Brought back to live in https://github.com/freeacs/freeacs/commit/4e4585859baca1ff086ee5badbc5d83ce47e4d7e

**Comment by jarlah** [comment]
Fixed. do a docker-compose -p freeacs down and docker-compose -p freeacs up -d (i think it will pull latest images). Monitor should now work.

**Comment by jpVm5jYYRE1VIKL** [comment]
nope i cannot confirm that it started to work . i pulled latest version images and 
after it i did "docker-compose -p freeacs up --force-recreate -d" and still have same issue.

**Comment by jarlah** [comment]
how are you running the docker compose file? i introduced a new file, .env that needs to be in the same directory as docker-compose.yml. Either download that file or clone the repo. Its in the scripts folder. 

You need to run docker-compose -p freeacs pull .. figured that out for myself now :P

**Comment by jarlah** [comment]
![screenshot_20180801_160838](https://user-images.githubusercontent.com/404102/43526753-3ed4514e-95a5-11e8-8735-e2b6b9156459.png)

**Comment by jarlah** [comment]
i needed an .env file to be able to override host for syslog server and generally being able to override env variables in docker-compose. Oh .. you need to redownload the docker compose file. Its changed

**Comment by jarlah** [comment]
see https://github.com/freeacs/freeacs/issues/162 for how to get stuff working after my last changes.
