### ISSUE TITLE
Building dbi 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by baronkis** [freeacs/freeacs#348]
I trying install freeacs 3.1 on Ubuntu 16.04.6 LTS but I have problem. I give errors with log about mysqld cannot run in root mode. What am I doing wrong?

/tmp/MariaDB4j/base/bin/mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!

[INFO] -----------------------< com.github.freeacs:dbi >-----------------------
[INFO] Building dbi 3.1-SNAPSHOT                                         [4/14]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dbi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dbi ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dbi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ dbi ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ dbi ---
[INFO] Surefire report directory: /tmp/freeacs/dbi/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.freeacs.dbi.report.TmsConverterTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.28 sec
Running com.github.freeacs.dbi.JobsTest
2019-08-31 16:57:03 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld: 2019-08-31 16:57:03 139949906016064 [ERROR] Aborting
2019-08-31 16:57:03 [Exec Default Executor] ERROR c.v.exec.LoggingExecuteResultHandler - Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/freeacs/dbi/db/38025c08-2029-4e34-8871-eb15588c39b6, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base) failed unexpectedly
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:748)
2019-08-31 16:57:03 [main] ERROR ch.vorburger.mariadb4j.DB - failed to start mysqld
ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/freeacs/dbi/db/38025c08-2029-4e34-8871-eb15588c39b6, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2019-08-31 16:57:03 139949906016064 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.2.11-MariaDB) starting as process 11907 ...
/tmp/MariaDB4j/base/bin/mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!
2019-08-31 16:57:03 139949906016064 [ERROR] Aborting

        at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:278)
        at ch.vorburger.mariadb4j.DB.start(DB.java:153)
        at com.github.freeacs.common.util.AbstractEmbeddedDataSourceHelper.setUpBeforeClass(AbstractEmbeddedDataSourceHelper.java:26)
        at com.github.freeacs.dbi.BaseDBITest.init(BaseDBITest.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by jarlah** [comment]
I need to think about this. First, i am not sure if we need mysql testing at all. Second i have just risen from the grave of inactivity. So give me some time to process all issues
